version: '{build}'

configuration: Release

platform: Any CPU

before_build:
- cmd: set ASPNETCORE_ENVIRONMENT=Production
- cmd: nuget restore

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017