version: '{build}'

configuration: Release

platform: Any CPU

before_build:
- cmd: set ASPNETCORE_ENVIRONMENT=Production
- cmd: nuget restore

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

after_build:
  - cmd: dotnet pack osu-framework-native /p:Version=0.0.%APPVEYOR_BUILD_VERSION%
artifacts:
  - path: osu-framework-native/bin/Any CPU/Release/*.nupkg